"""The robot's kinematic model, as measured from this controller.

WHY THIS EXISTS. No URDF matched to this firmware is published anywhere. The
vendor ships one for a different software version whose rounded lengths
(395.01, 102.1) are measurably WORSE than the controller's own, and every
tool a robot developer reaches for -- RViz, Foxglove, three.js, a digital
shadow, a reachability study -- wants a URDF. Serving one from the gateway
means those tools work straight off `/ws/state` with nothing else installed.

PROVENANCE. Fitted against this controller's own `GetForwardKin` over 59
sampled joint configurations: 0.0000 mm RMS, 0.000035 mm worst case. The
structure follows the vendor's fr5v6 URDF; the lengths are the controller's.
Do NOT "correct" these toward the published URDF -- that makes the model
worse, and the residual above is the evidence.

WHAT IT IS NOT. The visual geometry here is a set of primitives derived from
the link lengths so a viewer shows a recognisable arm. It is a stand-in, not
the real shell: the actual meshes are FAIR-INNOVATION's collision meshes and
ship with `fairino-fws-console`. `?visuals=none` omits them entirely, which
is what you want for anything that computes rather than draws.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any
from xml.sax.saxutils import escape

MM = 1000.0                       # URDF is metres; this model is millimetres


@dataclass(frozen=True)
class Link:
    """One joint's fixed transform, applied BEFORE its rotation.

    Each frame is: translate `xyz` in the parent frame, twist about x by
    `twist_rad`, then rotate about z by the joint angle. That is exactly a
    URDF joint origin plus a z axis, which is why this maps across without
    reinterpretation.
    """

    name: str
    xyz_mm: tuple[float, float, float]
    twist_rad: float


# Measured. See the module docstring before changing a number here.
FR5_CHAIN: tuple[Link, ...] = (
    Link("j1", (0.0, 0.0, 0.0), 0.0),
    Link("j2", (0.0, 0.0, 152.0), 1.5707963267948966),
    Link("j3", (-425.0, 0.0, 0.0), 0.0),
    Link("j4", (-395.0, 0.0, 0.0), 0.0),
    Link("j5", (0.0, 0.0, 102.0), 1.5707963267948966),
    Link("j6", (0.0, 0.0, 102.0), -1.5707963267948966),
)
FLANGE_MM: tuple[float, float, float] = (0.0, 0.0, 100.0)
REACH_MM = 922.0

MODEL_INFO: dict[str, Any] = {
    "model": "fr5",
    "provenance": "measured",
    "fitted_against": "this controller's own GetForwardKin",
    "samples": 59,
    "rms_mm": 0.0,
    "worst_case_mm": 0.000035,
    "reach_mm": REACH_MM,
    "units": "the model is millimetres; the URDF is metres, as URDF requires",
    "note": ("Structure follows the vendor's fr5v6 URDF; the lengths are the "
             "controller's own and are measurably better than the published "
             "ones. Visual geometry in the URDF is a primitive stand-in, not "
             "the real shell -- the meshes ship with fairino-fws-console."),
    "verification": (
        "The CHAIN is hardware-verified: fairino-fws-console renders from "
        "these same numbers and compares its forward kinematics against the "
        "controller-reported TCP on every frame, holding 0.00 mm on the live "
        "arm. This URDF is a transcription of that chain, and the "
        "transcription is pinned by test (tests/test_model.py). What has NOT "
        "been done is an end-to-end check of this document in a URDF consumer "
        "against the live arm -- treat the rendering as unverified until it "
        "has."),
}


def _m(v: float) -> str:
    """Millimetres to metres, printed without exponent noise."""
    return f"{v / MM:.6f}"


def _joint_limits(soft_limits: list[tuple[float, float]] | None,
                  i: int) -> tuple[float, float]:
    """Radians. Falls back to a full turn when the controller did not say.

    A fabricated tight limit would be worse than a loose one: a planner that
    trusts it would refuse reachable poses.
    """
    import math
    if soft_limits and i < len(soft_limits):
        lo, hi = soft_limits[i]
        return math.radians(lo), math.radians(hi)
    return -math.pi * 2, math.pi * 2


def urdf(*, name: str = "fr5", visuals: str = "primitives",
         soft_limits: list[tuple[float, float]] | None = None) -> str:
    """Render the measured chain as URDF.

    `soft_limits` are the controller's own, in degrees, when the caller has
    them -- so the served model refuses the same poses the real arm does.
    """
    if visuals not in ("primitives", "none"):
        raise ValueError("visuals must be 'primitives' or 'none'")

    out: list[str] = [
        '<?xml version="1.0"?>',
        f"<!-- Generated by FWS from a model MEASURED against this "
        f"controller: {MODEL_INFO['samples']} GetForwardKin samples, "
        f"{MODEL_INFO['rms_mm']} mm RMS. -->",
        "<!-- Visual geometry is a primitive stand-in derived from the link "
        "lengths, NOT the real shell. -->",
        "<!-- The collision meshes ship with fairino-fws-console. Use "
        "?visuals=none for pure kinematics. -->",
        f'<robot name="{escape(name)}">',
        '  <link name="base_link"/>',
    ]

    parent = "base_link"
    for i, link in enumerate(FR5_CHAIN):
        child = f"{link.name}_link"
        lo, hi = _joint_limits(soft_limits, i)
        out.append(f'  <joint name="{link.name}" type="revolute">')
        out.append(f'    <parent link="{parent}"/>')
        out.append(f'    <child link="{child}"/>')
        out.append(f'    <origin xyz="{_m(link.xyz_mm[0])} '
                   f'{_m(link.xyz_mm[1])} {_m(link.xyz_mm[2])}" '
                   f'rpy="{link.twist_rad:.10f} 0 0"/>')
        out.append('    <axis xyz="0 0 1"/>')
        out.append(f'    <limit lower="{lo:.6f}" upper="{hi:.6f}" '
                   f'effort="0" velocity="3.14"/>')
        out.append("  </joint>")

        out.append(f'  <link name="{child}">')
        if visuals == "primitives":
            # A capsule-ish cylinder spanning to the NEXT frame, so the arm
            # reads as an arm. Length comes from the following link's offset;
            # the last one uses the flange.
            nxt = (FR5_CHAIN[i + 1].xyz_mm if i + 1 < len(FR5_CHAIN)
                   else FLANGE_MM)
            span = max(abs(nxt[0]), abs(nxt[1]), abs(nxt[2]))
            if span > 1.0:
                axis = max(range(3), key=lambda k: abs(nxt[k]))
                half = nxt[axis] / 2.0
                xyz = [0.0, 0.0, 0.0]
                xyz[axis] = half
                rpy = {0: "0 1.5707963 0", 1: "1.5707963 0 0",
                       2: "0 0 0"}[axis]
                out.append("    <visual>")
                out.append(f'      <origin xyz="{_m(xyz[0])} {_m(xyz[1])} '
                           f'{_m(xyz[2])}" rpy="{rpy}"/>')
                out.append("      <geometry>")
                out.append(f'        <cylinder radius="0.04" '
                           f'length="{_m(abs(nxt[axis]))}"/>')
                out.append("      </geometry>")
                out.append("    </visual>")
        out.append("  </link>")
        parent = child

    # The flange, and the TCP frame every pose in the API is expressed in.
    out.append('  <joint name="flange" type="fixed">')
    out.append(f'    <parent link="{parent}"/>')
    out.append('    <child link="flange_link"/>')
    out.append(f'    <origin xyz="{_m(FLANGE_MM[0])} {_m(FLANGE_MM[1])} '
               f'{_m(FLANGE_MM[2])}" rpy="0 0 0"/>')
    out.append("  </joint>")
    out.append('  <link name="flange_link"/>')
    out.append("</robot>")
    return "\n".join(out) + "\n"
