#!/usr/bin/env python3
"""The full program loop: generate Lua, upload, validate, load, run, watch.

THIS MOVES THE ARM against real hardware. Read SAFETY.md first.

Why a program at all? On this firmware every motion except jogging is a Lua
program running on the controller. There is no "move to pose" RPC you can
safely stream at cycle rate -- the command channel is single-client and
serialised. So the honest pattern is: build a program, let the controller
compile it, run it, watch the telemetry.

The poses here are LITERAL, on purpose. Literal targets are the ones FWS can
pre-flight through inverse kinematics before anything moves; a program that
refers to named points from the controller's own database cannot be checked
the same way.
"""
from __future__ import annotations

import time

from _common import connect, show, step

# A safe, small demonstration around the simulator's home pose. Adjust for a
# real cell -- and validate before you run (step 3 does exactly that).
# (joints, tcp) pairs. Both are literal: the gateway pre-flights the target
# before anything moves, which it cannot do for a named point.
HOME = ([0.0, -90.0, 90.0, -90.0, -90.0, 0.0],
        [495.0, 0.0, -273.0, -90.0, -90.0, 0.0])
ABOVE_PICK = ([15.0, -85.0, 85.0, -90.0, -90.0, 0.0],
              [478.0, 128.0, -230.0, -90.0, -90.0, 0.0])
ABOVE_PLACE = ([-15.0, -85.0, 85.0, -90.0, -90.0, 0.0],
               [478.0, -128.0, -230.0, -90.0, -90.0, 0.0])

PROGRAM_NAME = "example_pick_place.lua"


def movej(joints, tcp, speed=20):
    """One MoveJ with a literal target: 29 flat arguments.

    Not a table -- the six joint angles and six Cartesian values are spread
    as individual arguments. The arity is 29 on this firmware, PROBED rather
    than read off a manual, and the controller does not ignore a wrong count
    safely. This is exactly why FWS generates the call instead of asking you
    to remember it: see GET /api/v1/lua/functions/MoveJ for the prototype.
    """
    j = ", ".join(f"{v:.3f}" for v in joints)
    c = ", ".join(f"{v:.3f}" for v in tcp)
    #        joints(6) tcp(6) tool wobj speed acc ovl  + 12 trailing
    return (f"MoveJ({j}, {c}, 0, 0, {speed}, 100, 100, "
            f"0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0)")


def build_program() -> str:
    """A flat list of statements -- no `function main() ... end` wrapper.

    A Fairino program IS the statement list; wrapping it in main() and
    calling it fails to compile, because `main` is not a global the
    controller's Lua environment provides.
    """
    lines = [
        "-- generated by examples/03_pick_and_place.py",
        "",
        "-- move to a known start",
        movej(*HOME),
        "-- above the pick",
        movej(*ABOVE_PICK),
        "-- close the gripper here (SetDO, or a gripper call for your tool)",
        "WaitMs(200)",
        "-- above the place",
        movej(*ABOVE_PLACE),
        "-- open the gripper here",
        "WaitMs(200)",
        "-- home again",
        movej(*HOME),
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    with connect("Generate, validate, upload and run a Lua program") as (
            fws, _args):
        src = build_program()

        step(1, "The program we generated")
        for line in src.splitlines():
            print(f"      {line}")

        step(2, "Take the leases this needs")
        # motion to move, program to load and run. Holding a subset means
        # half the flow fails with 423s that look like bugs.
        fws.take_control(domains=("motion", "program"), client_id="example-pnp")
        show("leases", "motion + program")

        step(3, "Upload it -- the controller compiles it")
        # A rejected program returns the compiler's real complaint, recovered
        # from the controller log: the upload call itself only says 0 or -1.
        status, body = fws.put(f"/api/v1/programs/{PROGRAM_NAME}",
                               {"content": src, "overwrite": True,
                                "confirm": True})
        show("status", status)
        if status not in (200, 201):
            show("gateway said", body)
            return 1
        show("uploaded", PROGRAM_NAME)

        step(4, "Pre-flight every literal target before anything moves")
        # Solves each pose backwards through the controller's own kinematics
        # against the soft limits it reports. `partial` means some target
        # could not be resolved -- not that it is safe.
        status, report = fws.post(f"/api/v1/programs/{PROGRAM_NAME}/validate")
        if status == 200 and report:
            show("checked", report.get("checked"))
            show("verdict", report.get("verdict", report.get("ok")))
            for problem in (report.get("problems") or [])[:5]:
                print(f"      ! {problem}")
            if report.get("partial"):
                show("note", "PARTIAL -- some targets were not resolvable")
        else:
            show("validate", f"{status}: {report}")

        step(5, "Load and run it")
        fws.post(f"/api/v1/programs/{PROGRAM_NAME}/load")
        status, body = fws.post("/api/v1/execution/run", {"confirm": True})
        show("run status", status)
        if status != 200:
            show("gateway said", body)
            return 1

        step(6, "Watch it go")
        # The simulator does not execute Lua -- it accepts, compiles and
        # reports state, so the pose below will not change against it. On
        # hardware this is where you see the arm move.
        for _ in range(20):
            time.sleep(0.25)
            _s, ex = fws.get("/api/v1/execution")
            _s2, st = fws.get("/api/v1/state")
            joints = (st or {}).get("joints") or []
            ex = ex or {}
            print(f"      state {ex.get('state'):<8} line "
                  f"{ex.get('current_line'):<4} J1 "
                  f"{(joints or [0])[0]:7.2f}", flush=True)
            if ex.get("state") == "stopped":
                break

        step(7, "Stop and release")
        fws.post("/api/v1/execution/stop")
        fws.release()
        show("done", "program left on the controller for inspection")

        print("\nNext: 04_handle_faults.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
