"""Controller error codes — GENERATED FILE, DO NOT EDIT BY HAND.

Regenerate with:

Source: Fairino Controller Communication Command Protocol manual, section 10.
  sha256: 55e18ffe689923710cb47601b4b64ba205208d2ef2eec197617084fe2ccbe34f

TWO CAVEATS, both carried deliberately into every lookup:

  1. The manual is a machine translation from Chinese. Descriptions read
     awkwardly; they have not been rewritten, because paraphrasing a fault
     description risks changing what it means.
  2. The manual documents V3.9.8. This controller runs v3.8.5.1, for which
     Fairino publishes no manual at all. A code's meaning here is DOCUMENTED,
     not verified, unless it appears in OBSERVED below -- those were seen on
     real hardware and outrank the manual.
"""
from __future__ import annotations

from typing import Any

from dataclasses import dataclass


@dataclass(frozen=True)
class ErrorCode:
    code: int
    description: str
    process: str = ""
    seen_context: str = ""      # what we were doing when this code appeared
    verified: bool = False      # seen on our hardware at least once

    @property
    def source(self) -> str:
        return "manual-v3.9.8 + observed" if self.verified else "manual-v3.9.8"


ERROR_CODES: dict[int, ErrorCode] = {
    0: ErrorCode(
        code=0,
        description="success",
        process="",
        seen_context="",
        verified=False,
    ),
    3: ErrorCode(
        code=3,
        description="The number of parameters is abnormal",
        process="Check the number of interface parameters",
        seen_context="",
        verified=False,
    ),
    4: ErrorCode(
        code=4,
        description="The parameter value is abnormal",
        process="Check the type or range of parameter values",
        seen_context="",
        verified=False,
    ),
    5: ErrorCode(
        code=5,
        description="The tpd timer failed to start",
        process="Check the TPD timer parameter Settings",
        seen_context="",
        verified=False,
    ),
    6: ErrorCode(
        code=6,
        description="The tpd timer failed to close",
        process="Check the TPD timer parameter Settings",
        seen_context="",
        verified=False,
    ),
    7: ErrorCode(
        code=7,
        description="The tpd file creation failed",
        process="Check the TPD file name",
        seen_context="",
        verified=False,
    ),
    8: ErrorCode(
        code=8,
        description="The tpd file does not exist",
        process="Check whether the TPD trajectory file exists or whether the trajectory name is correct",
        seen_context="",
        verified=False,
    ),
    9: ErrorCode(
        code=9,
        description="The tpd file name was not sent successfully",
        process="Check that the TPD track name is correct",
        seen_context="",
        verified=False,
    ),
    10: ErrorCode(
        code=10,
        description="The content of tpd file is sent failed",
        process="Check that the TPD file is correct",
        seen_context="",
        verified=False,
    ),
    11: ErrorCode(
        code=11,
        description="The program is abnormal and parsing stops",
        process="Check the contents of the procedure and the instructions executed when the procedure terminates",
        seen_context="",
        verified=False,
    ),
    12: ErrorCode(
        code=12,
        description="The contents of the tpd file are inconsistent",
        process="Check the contents of the TPD file",
        seen_context="",
        verified=False,
    ),
    13: ErrorCode(
        code=13,
        description="The number of points in the tpd file is abnormal",
        process="Check the contents of the TPD file",
        seen_context="",
        verified=False,
    ),
    14: ErrorCode(
        code=14,
        description="The instruction execution failed",
        process="Check whether the web interface is faulty or whether the status feedback is faulty",
        seen_context="seen when the controller was faulted: position getters refused until ResetAllError",
        verified=True,
    ),
    15: ErrorCode(
        code=15,
        description="The number of tpd record points is out of limit",
        process="Re-record",
        seen_context="",
        verified=False,
    ),
    16: ErrorCode(
        code=16,
        description="The agreement has been loaded",
        process="Do not reload the protocol repeatedly",
        seen_context="",
        verified=False,
    ),
    17: ErrorCode(
        code=17,
        description="The agreement is not loaded",
        process="Please load the protocol first",
        seen_context="",
        verified=False,
    ),
    18: ErrorCode(
        code=18,
        description="The program is running",
        process="Stop the program before proceeding with other operations",
        seen_context="",
        verified=False,
    ),
    19: ErrorCode(
        code=19,
        description="The posture sensor communication is abnormal",
        process="Check the connection between the robot and the sensor network and the loading of the sensor protocol",
        seen_context="",
        verified=False,
    ),
    20: ErrorCode(
        code=20,
        description="The tool is not set for welding",
        process="Swing welding requires the tool coordinate system to be set with a tool number other than 0",
        seen_context="",
        verified=False,
    ),
    21: ErrorCode(
        code=21,
        description="The external shaft is not deactivated",
        process="Please remove the active extension shaft first",
        seen_context="",
        verified=False,
    ),
    22: ErrorCode(
        code=22,
        description="The three-point method does not set up the tool",
        process="Please set the tool coordinate system first",
        seen_context="",
        verified=False,
    ),
    23: ErrorCode(
        code=23,
        description="Position sensor data acquisition failed",
        process="Check the connection between the robot and the sensor network and the loading of the sensor protocol",
        seen_context="",
        verified=False,
    ),
    24: ErrorCode(
        code=24,
        description="Eight-point method-the first four points have too much posture change",
        process="Please reduce the value of the first four points of attitude change",
        seen_context="",
        verified=False,
    ),
    25: ErrorCode(
        code=25,
        description="Calculation failed",
        process="Redeploy or re-identify",
        seen_context="",
        verified=False,
    ),
    26: ErrorCode(
        code=26,
        description="Eight-point method-not switched to the base coordinate system",
        process="Please switch to the base coordinate system (tool coordinate system with tool number 0) first",
        seen_context="",
        verified=False,
    ),
    27: ErrorCode(
        code=27,
        description="Eight-point method-the",
        process="Please re-calibrate",
        seen_context="",
        verified=False,
    ),
    28: ErrorCode(
        code=28,
        description="calculation result is abnormal The results of inverse kinematics calculation are abnormal",
        process="Check whether the position is reasonable",
        seen_context="",
        verified=False,
    ),
    29: ErrorCode(
        code=29,
        description="ServoJ Joint overlimit",
        process="Check that the joint data is within a reasonable range",
        seen_context="",
        verified=False,
    ),
    30: ErrorCode(
        code=30,
        description="If the reset fails, please restart",
        process="Please disconnect the power and restart the control box",
        seen_context="",
        verified=False,
    ),
    31: ErrorCode(
        code=31,
        description="If the emergency stop button is released, please disconnect power and",
        process="Please disconnect power and restart the control box",
        seen_context="",
        verified=False,
    ),
    32: ErrorCode(
        code=32,
        description="restart the control box Joint over-limit",
        process="Switch to drag mode and move the joint into the soft limit range",
        seen_context="",
        verified=False,
    ),
    33: ErrorCode(
        code=33,
        description="The external axis is not at zero, and the guide and resolution settings fail",
        process="Please check the external shaft setting",
        seen_context="",
        verified=False,
    ),
    34: ErrorCode(
        code=34,
        description="Workpiece number error",
        process="Please check whether the workpiece number is reasonable",
        seen_context="",
        verified=False,
    ),
    35: ErrorCode(
        code=35,
        description="Please switch to workpiece number 0",
        process="Please switch to the workpiece coordinate system of workpiece number 0",
        seen_context="",
        verified=False,
    ),
    36: ErrorCode(
        code=36,
        description="The file name is too long",
        process="Please reduce the length of the file name",
        seen_context="",
        verified=False,
    ),
    37: ErrorCode(
        code=37,
        description="Tool number error",
        process="Please check whether the tool number is reasonable",
        seen_context="",
        verified=False,
    ),
    38: ErrorCode(
        code=38,
        description="Strange posture",
        process="Please change your posture",
        seen_context="",
        verified=False,
    ),
    39: ErrorCode(
        code=39,
        description="socket The name is invalid",
        process="Please check the Socket name",
        seen_context="",
        verified=False,
    ),
    40: ErrorCode(
        code=40,
        description="Speed percentage exceeds limit",
        process="Check whether the speed percentage is reasonable",
        seen_context="",
        verified=False,
    ),
    41: ErrorCode(
        code=41,
        description="The external shaft has not returned to zero",
        process="Please check the external shaft setting",
        seen_context="",
        verified=False,
    ),
    42: ErrorCode(
        code=42,
        description="The posture changes too much",
        process="Insert intermediate postures for transition",
        seen_context="",
        verified=False,
    ),
    43: ErrorCode(
        code=43,
        description="The conveyor belt detection switch DI is not configured",
        process="Please configure the conveyor belt DI detection port",
        seen_context="",
        verified=False,
    ),
    44: ErrorCode(
        code=44,
        description="The robot's attitude Angle is out of limit",
        process="Please check the target posture setting",
        seen_context="",
        verified=False,
    ),
    45: ErrorCode(
        code=45,
        description="The external axis is not activated",
        process="Please check the external shaft setting",
        seen_context="",
        verified=False,
    ),
    46: ErrorCode(
        code=46,
        description="The synchronization function requires calibration of the external axis",
        process="Please check the external shaft setting",
        seen_context="",
        verified=False,
    ),
    47: ErrorCode(
        code=47,
        description="The external driver information configuration failed",
        process="Please check the external shaft setting",
        seen_context="",
        verified=False,
    ),
    48: ErrorCode(
        code=48,
        description="The external shaft drive information configuration timeout occurred",
        process="Please check the external shaft setting",
        seen_context="",
        verified=False,
    ),
    49: ErrorCode(
        code=49,
        description="External shaft error cannot be enabled",
        process="Please check the status of the external shaft",
        seen_context="",
        verified=False,
    ),
    50: ErrorCode(
        code=50,
        description="Failed to obtain information from the external axis driver",
        process="Please check the status of the external shaft",
        seen_context="",
        verified=False,
    ),
    51: ErrorCode(
        code=51,
        description="The external shaft driver information acquisition timeout",
        process="Please check the status of the external shaft",
        seen_context="",
        verified=False,
    ),
    52: ErrorCode(
        code=52,
        description="The synchronization function cannot be used for single-step operation",
        process="Please check the external shaft setting",
        seen_context="",
        verified=False,
    ),
    59: ErrorCode(
        code=59,
        description="The force/torque sensor is not activated",
        process="Stimulate the activity sensor",
        seen_context="",
        verified=False,
    ),
    60: ErrorCode(
        code=60,
        description="The reference coordinate system of the force/torque sensor has not been switched to the tool",
        process="Switch the force sensor coordinate system to the tool",
        seen_context="",
        verified=False,
    ),
    61: ErrorCode(
        code=61,
        description="The force/torque sensor is not set to zero",
        process="Please set the zero point of force/torque sensor first",
        seen_context="",
        verified=False,
    ),
    62: ErrorCode(
        code=62,
        description="The load of the torque sensor is not set to zero",
        process="Please first reset the load of the force/torque sensor",
        seen_context="",
        verified=False,
    ),
    63: ErrorCode(
        code=63,
        description="Failed to obtain system time",
        process="Contact the after-sales engineer to view the controller log",
        seen_context="",
        verified=False,
    ),
    64: ErrorCode(
        code=64,
        description="Not added to instruction queue",
        process="Contact the after-sales engineer to view the controller log",
        seen_context="",
        verified=False,
    ),
    66: ErrorCode(
        code=66,
        description="The midpoint 1 of the circular/spiral instruction is incorrect",
        process="Check whether the data at midpoint 1 is correct",
        seen_context="",
        verified=False,
    ),
    67: ErrorCode(
        code=67,
        description="The midpoint 2 of the circular/spiral instruction is incorrect",
        process="Check whether the data at midpoint 2 is correct",
        seen_context="",
        verified=False,
    ),
    68: ErrorCode(
        code=68,
        description="The midpoint of the circular/spiral instruction 3 is incorrect",
        process="Check whether the data at the midpoint 3 is correct",
        seen_context="",
        verified=False,
    ),
    69: ErrorCode(
        code=69,
        description="The midpoint of the arc instruction is incorrect",
        process="Check that the midpoint data is correct",
        seen_context="",
        verified=False,
    ),
    70: ErrorCode(
        code=70,
        description="The target point of the arc instruction is incorrect",
        process="Check whether the target point data is correct",
        seen_context="",
        verified=False,
    ),
    73: ErrorCode(
        code=73,
        description="Claw movement error",
        process="Check whether the communication status of the clamp is normal",
        seen_context="",
        verified=False,
    ),
    74: ErrorCode(
        code=74,
        description="The linear command point is incorrect",
        process="Check whether the checkpoint data is correct",
        seen_context="seen when MoveL was rejected with a 33-element argument array on firmware v3.8.5.1",
        verified=True,
    ),
    75: ErrorCode(
        code=75,
        description="Channel error",
        process="Check that the IO number is within the range",
        seen_context="",
        verified=False,
    ),
    76: ErrorCode(
        code=76,
        description="Waiting for timeout",
        process="Check whether the IO signal is input or whether the wiring is correct",
        seen_context="",
        verified=False,
    ),
    82: ErrorCode(
        code=82,
        description="TPD instruction point error",
        process="Re-record the teaching path",
        seen_context="",
        verified=False,
    ),
    83: ErrorCode(
        code=83,
        description="The TPD directive tool is not compatible with the current tool",
        process="Change to the tool coordinate system used for TPD teaching",
        seen_context="",
        verified=False,
    ),
    84: ErrorCode(
        code=84,
        description="Weld seam location failed",
        process="Please check the laser sensor parameter configuration to ensure that the sensor can identify the weld seam",
        seen_context="",
        verified=False,
    ),
    85: ErrorCode(
        code=85,
        description="Line directive error",
        process="Please check whether the position parameters of the instruction point, tool number and workpiece number are configured",
        seen_context="",
        verified=False,
    ),
    90: ErrorCode(
        code=90,
        description="External axis configuration file check failed",
        process="Contact the after-sales engineer to check the controller log",
        seen_context="",
        verified=False,
    ),
    91: ErrorCode(
        code=91,
        description="The version of the peripheral configuration file does not match",
        process="Contact the after-sales engineer to view the controller log",
        seen_context="",
        verified=False,
    ),
    92: ErrorCode(
        code=92,
        description="The peripheral configuration file is read failed",
        process="Contact the after-sales engineer to view the controller log",
        seen_context="",
        verified=False,
    ),
    93: ErrorCode(
        code=93,
        description="The number of spline instruction points is out of",
        process="Please reduce the number of spline instruction points",
        seen_context="",
        verified=False,
    ),
    94: ErrorCode(
        code=94,
        description="limit The spline instruction point is incorrect",
        process="Check whether the checkpoint data is correct",
        seen_context="",
        verified=False,
    ),
    95: ErrorCode(
        code=95,
        description="The spline parameters are incorrect",
        process="Check whether the spline parameters are reasonable",
        seen_context="",
        verified=False,
    ),
    96: ErrorCode(
        code=96,
        description="Wire positioning failed",
        process="Please check the welding wire location parameter configuration",
        seen_context="",
        verified=False,
    ),
    97: ErrorCode(
        code=97,
        description="The data recorded is empty",
        process="Please line up for data recording",
        seen_context="",
        verified=False,
    ),
    98: ErrorCode(
        code=98,
        description="The main program is not configured",
        process="Please configure the main program first",
        seen_context="",
        verified=False,
    ),
    99: ErrorCode(
        code=99,
        description="The security stop has been triggered",
        process="Please check the status of the safety stop signal",
        seen_context="",
        verified=False,
    ),
    100: ErrorCode(
        code=100,
        description="The job origin has not been configured",
        process="Please configure the origin of the job first",
        seen_context="",
        verified=False,
    ),
    101: ErrorCode(
        code=101,
        description="The robot is not enabled",
        process="Please enable the robot first",
        seen_context="",
        verified=False,
    ),
    106: ErrorCode(
        code=106,
        description="The external shaft is not enabled",
        process="Enable the external shaft first",
        seen_context="",
        verified=False,
    ),
    108: ErrorCode(
        code=108,
        description="The starting point of the helix command is incorrect",
        process="Check that the starting point data is correct",
        seen_context="",
        verified=False,
    ),
    110: ErrorCode(
        code=110,
        description="Please close the drag configuration-impedance callback to enter the interference area",
        process="Please close the drag configuration to enter the interference area",
        seen_context="",
        verified=False,
    ),
    111: ErrorCode(
        code=111,
        description="Please turn off the drag teaching lock free degree function",
        process="Please turn off the drag teaching lock freedom function",
        seen_context="",
        verified=False,
    ),
    112: ErrorCode(
        code=112,
        description="The positioning posture cannot be reached",
        process="Check whether the target position is reasonable",
        seen_context="seen from GetInverseKin for an unreachable or near-singular target",
        verified=True,
    ),
    114: ErrorCode(
        code=114,
        description="The DMP instruction point is incorrect",
        process="Please check the value of the DMP instruction position",
        seen_context="",
        verified=False,
    ),
    115: ErrorCode(
        code=115,
        description="Circular motion instruction point error",
        process="Please check the target point information of circular motion",
        seen_context="",
        verified=False,
    ),
    116: ErrorCode(
        code=116,
        description="The extended axis peripheral communication driver is not loaded",
        process="Please load the extension shaft communication first",
        seen_context="seen from GetAuxDI / GetAuxAI on a controller without auxiliary I/O",
        verified=True,
    ),
    118: ErrorCode(
        code=118,
        description="The load weight of the force sensor is incorrect",
        process="Please check the load weight parameter value under the force sensor",
        seen_context="",
        verified=False,
    ),
    119: ErrorCode(
        code=119,
        description="The load center of gravity is wrong under the force sensor",
        process="Please check the position parameter value of the load center of mass under the force sensor",
        seen_context="",
        verified=False,
    ),
    120: ErrorCode(
        code=120,
        description="The trajectory command point is incorrect",
        process="Please check the trajectory command point",
        seen_context="",
        verified=False,
    ),
    121: ErrorCode(
        code=121,
        description="The number of trajectory points is 0",
        process="Please check the trajectory command point",
        seen_context="",
        verified=False,
    ),
    122: ErrorCode(
        code=122,
        description="Joint torque exceeds limit",
        process="Please check whether the current robot load is too large",
        seen_context="",
        verified=False,
    ),
    123: ErrorCode(
        code=123,
        description="Please exit the drag mode first",
        process="Please exit the drag mode",
        seen_context="",
        verified=False,
    ),
    124: ErrorCode(
        code=124,
        description="The extended axis parameters are not configured",
        process="Please configure the extended axis parameters first",
        seen_context="",
        verified=False,
    ),
    125: ErrorCode(
        code=125,
        description="Recovery of welding failed-the original program failed",
        process="Contact the after-sales engineer to view the controller log",
        seen_context="",
        verified=False,
    ),
    126: ErrorCode(
        code=126,
        description="Recovery welding failed-unable to obtain the",
        process="Contact the after-sales engineer to view the controller log",
        seen_context="",
        verified=False,
    ),
    127: ErrorCode(
        code=127,
        description="restart arc point Restore welding failed-unable to generate restore program",
        process="Contact the after-sales engineer to view the controller log",
        seen_context="",
        verified=False,
    ),
    128: ErrorCode(
        code=128,
        description="Not in manual mode / stopped",
        process="Please switch to manual mode",
        seen_context="",
        verified=False,
    ),
    129: ErrorCode(
        code=129,
        description="Please switch to the new dynamics mode first",
        process="Please switch to the new dynamics mode first",
        seen_context="",
        verified=False,
    ),
    130: ErrorCode(
        code=130,
        description="The point table does not exist",
        process="Check whether the name of the checkpoint is correct",
        seen_context="",
        verified=False,
    ),
    133: ErrorCode(
        code=133,
        description="Please switch to drag mode / force sensor assisted drag mode first",
        process="Please switch to drag mode / force sensor assisted drag mode first",
        seen_context="",
        verified=False,
    ),
    134: ErrorCode(
        code=134,
        description="The force/torque sensor is unloaded",
        process="Check the load of the force/torque sensor",
        seen_context="",
        verified=False,
    ),
    135: ErrorCode(
        code=135,
        description="The inverse of the matrix of the force/torque sensor is abnormal",
        process="Contact the after-sales engineer to view the controller log",
        seen_context="",
        verified=False,
    ),
    138: ErrorCode(
        code=138,
        description="The detection switch DI is not configured",
        process="Please first configure the DI port of the detection switch",
        seen_context="",
        verified=False,
    ),
    139: ErrorCode(
        code=139,
        description="Please apply the extended axis coordinate system first",
        process="Please apply the extended axis coordinate system with a number other than 0 first",
        seen_context="",
        verified=False,
    ),
    140: ErrorCode(
        code=140,
        description="Please activate the current extension axis first",
        process="Please activate the current extension axis first",
        seen_context="",
        verified=False,
    ),
    143: ErrorCode(
        code=143,
        description="The teaching point information does not exist",
        process="Please check that the teaching point information exists",
        seen_context="seen from GetRobotTeachingPoint for a name that does not exist",
        verified=True,
    ),
    144: ErrorCode(
        code=144,
        description="The LUA file does not exist",
        process="Please check whether the LUA file exists",
        seen_context="",
        verified=False,
    ),
    151: ErrorCode(
        code=151,
        description="The joint configuration changed",
        process="Please check whether the joint configuration of the target position and the current position has changed",
        seen_context="",
        verified=False,
    ),
    152: ErrorCode(
        code=152,
        description="The spacing between welding instruction points is too small",
        process="Check whether the distance between the welding instruction point and the current point is too small",
        seen_context="",
        verified=False,
    ),
    153: ErrorCode(
        code=153,
        description="The spacing between arc instructions is too small",
        process="Please check the spacing of arc instruction points",
        seen_context="",
        verified=False,
    ),
    154: ErrorCode(
        code=154,
        description="The joint command point is incorrect",
        process="Please check the target point information of the instruction",
        seen_context="",
        verified=False,
    ),
    155: ErrorCode(
        code=155,
        description="The background program failed to start",
        process="Please check the content of the background program",
        seen_context="",
        verified=False,
    ),
    156: ErrorCode(
        code=156,
        description="The background program failed to pause",
        process="Contact the after-sales engineer to view the controller log",
        seen_context="",
        verified=False,
    ),
    157: ErrorCode(
        code=157,
        description="The background program failed to resume",
        process="Contact the after-sales engineer to check the controller log",
        seen_context="",
        verified=False,
    ),
    158: ErrorCode(
        code=158,
        description="The background program deletion failed",
        process="Contact the after-sales engineer to view the controller log",
        seen_context="",
        verified=False,
    ),
    159: ErrorCode(
        code=159,
        description="The number of background programs running exceeds 8",
        process="Please check the number of background programs running",
        seen_context="",
        verified=False,
    ),
    160: ErrorCode(
        code=160,
        description="The speed profile validation failed",
        process="Contact the after-sales engineer to view the controller log",
        seen_context="",
        verified=False,
    ),
    161: ErrorCode(
        code=161,
        description="Load profile validation failed",
        process="Contact the after-sales engineer to check the controller log",
        seen_context="",
        verified=False,
    ),
    162: ErrorCode(
        code=162,
        description="The extended axis in laser tracking cannot move asynchronously",
        process="Please adjust the extension shaft movement to synchronous movement",
        seen_context="",
        verified=False,
    ),
    163: ErrorCode(
        code=163,
        description="The welding procedure contains multiple while",
        process="Multiple while nesting cannot be restored from welding interruption",
        seen_context="",
        verified=False,
    ),
    164: ErrorCode(
        code=164,
        description="statements Segment welding information not returned",
        process="Please set the segment welding information",
        seen_context="",
        verified=False,
    ),
    165: ErrorCode(
        code=165,
        description="CNC communication error",
        process="Check CNC communication",
        seen_context="",
        verified=False,
    ),
    166: ErrorCode(
        code=166,
        description="CNC timeout",
        process="CNC timeout",
        seen_context="",
        verified=False,
    ),
    167: ErrorCode(
        code=167,
        description="CNC communication connection timed out",
        process="Check CNC communication",
        seen_context="",
        verified=False,
    ),
    168: ErrorCode(
        code=168,
        description="The number of monitored numeric variables exceeds the limit.",
        process="Check the number of monitored numeric variables",
        seen_context="",
        verified=False,
    ),
    169: ErrorCode(
        code=169,
        description="The number of character variables exceeds the limit.",
        process="Check the number of monitored character variables",
        seen_context="",
        verified=False,
    ),
    170: ErrorCode(
        code=170,
        description="Workpiece coordinate system not applied",
        process="Please check the workpiece coordinate system",
        seen_context="",
        verified=False,
    ),
    171: ErrorCode(
        code=171,
        description="All joints must be moved within the soft limit range",
        process="Please check the joint soft limits",
        seen_context="",
        verified=False,
    ),
    172: ErrorCode(
        code=172,
        description="Motion speed cannot be 0",
        process="Motion speed cannot be 0",
        seen_context="",
        verified=False,
    ),
    173: ErrorCode(
        code=173,
        description="Acceleration smoothing must be enabled for extended axis Blend motion",
        process="Acceleration smoothing must be enabled for extended axis Blend motion",
        seen_context="",
        verified=False,
    ),
    174: ErrorCode(
        code=174,
        description="Current robot model does not support this function",
        process="Current robot model does not support this function",
        seen_context="",
        verified=False,
    ),
    175: ErrorCode(
        code=175,
        description="Socket not configured",
        process="Please configure socket connection information",
        seen_context="",
        verified=False,
    ),
    176: ErrorCode(
        code=176,
        description="Socket communication connected",
        process="Socket communication is connected",
        seen_context="",
        verified=False,
    ),
    177: ErrorCode(
        code=177,
        description="Socket communication not connected",
        process="Please check the socket connection",
        seen_context="",
        verified=False,
    ),
    178: ErrorCode(
        code=178,
        description="Firmware version too high, current software version not supported",
        process="Firmware version is too high, current software version does not support it",
        seen_context="",
        verified=False,
    ),
    179: ErrorCode(
        code=179,
        description="Firmware version too low, current software version not supported",
        process="Firmware version is too low, current software version does not support it",
        seen_context="",
        verified=False,
    ),
    180: ErrorCode(
        code=180,
        description="G-code file cannot be opened",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    181: ErrorCode(
        code=181,
        description="G-code parsing failed",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    182: ErrorCode(
        code=182,
        description="Given physical speed exceeds limit",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    183: ErrorCode(
        code=183,
        description="Given physical acceleration exceeds limit",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    184: ErrorCode(
        code=184,
        description="External axis enable failed",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    185: ErrorCode(
        code=185,
        description="Motion stopped by error signal",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    186: ErrorCode(
        code=186,
        description="Motion stopped by emergency stop signal",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    187: ErrorCode(
        code=187,
        description="Collision level too low",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    188: ErrorCode(
        code=188,
        description="Force control and impedance control both enabled",
        process="Force control and impedance control are both enabled",
        seen_context="",
        verified=False,
    ),
    189: ErrorCode(
        code=189,
        description="Kernel upgrade version verification failed",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    190: ErrorCode(
        code=190,
        description="Kernel version upgrade failed",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    191: ErrorCode(
        code=191,
        description="Linear rack guide not",
        process="Linear rack guide is not activated",
        seen_context="",
        verified=False,
    ),
    192: ErrorCode(
        code=192,
        description="activated Current linear rack guide collision detection is only for upright installation",
        process="Current linear rack guide collision detection is only for upright installation",
        seen_context="",
        verified=False,
    ),
    193: ErrorCode(
        code=193,
        description="Torque control speed exceeds limit",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    194: ErrorCode(
        code=194,
        description="Torque control power exceeds limit",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    195: ErrorCode(
        code=195,
        description="FR30L base tilt angle must be 0",
        process="FR30L base tilt angle must be 0",
        seen_context="",
        verified=False,
    ),
    196: ErrorCode(
        code=196,
        description="The photoelectric sensor signal has not been triggered.",
        process="The photoelectric sensor signal has not been triggered.",
        seen_context="",
        verified=False,
    ),
    197: ErrorCode(
        code=197,
        description="The joint torque sensor has not completed zero-point or sensitivity calibration.",
        process="Calibrate the joint torque sensor again",
        seen_context="",
        verified=False,
    ),
    198: ErrorCode(
        code=198,
        description="The joint torque sensor exhibits an anomaly. Error in the interference",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    199: ErrorCode(
        code=199,
        description="range set for the multi-interference zone (multiple cubes can only be configured within the",
        process="The multi-cube can only be configured for interference within the specified range.",
        seen_context="",
        verified=False,
    ),
    200: ErrorCode(
        code=200,
        description="specified range) The robot is operating in intermittent mode.",
        process="The robot is operating in intermittent mode.",
        seen_context="",
        verified=False,
    ),
    201: ErrorCode(
        code=201,
        description="Swinging configuration file check failed",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    202: ErrorCode(
        code=202,
        description="Interference configuration file check failed",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    203: ErrorCode(
        code=203,
        description="End 485 communication error",
        process="Contact after-sales engineer to check controller logs",
        seen_context="",
        verified=False,
    ),
    204: ErrorCode(
        code=204,
        description="The instruction queue is full. Check the instruction sending frequency",
        process="Check the instruction sending frequency",
        seen_context="",
        verified=False,
    ),
    205: ErrorCode(
        code=205,
        description="The endpoint protocol is configured. Close it first",
        process="Close the endpoint protocol first",
        seen_context="",
        verified=False,
    ),
    206: ErrorCode(
        code=206,
        description="The adapted devices are configured. Clear the current adapted devices first",
        process="First, clear the currently adapted device",
        seen_context="",
        verified=False,
    ),
    207: ErrorCode(
        code=207,
        description="Automatic mode safe stop requires three-position enablement with the teaching device.",
        process="Automatic mode safe stop requires three-position enablement with the teaching device.",
        seen_context="",
        verified=False,
    ),
    208: ErrorCode(
        code=208,
        description="The current DI configuration is occupied and cannot be changed.",
        process="The current DI configuration is occupied and cannot be changed.",
        seen_context="",
        verified=False,
    ),
    209: ErrorCode(
        code=209,
        description="Not in tracking mode",
        process="Not in tracking mode",
        seen_context="",
        verified=False,
    ),
    210: ErrorCode(
        code=210,
        description="Conveyor belt calibration error",
        process="Calibrate the conveyor belt again.",
        seen_context="",
        verified=False,
    ),
}


def describe(code: int) -> dict[str, Any]:
    """Human-readable meaning for a controller error code.

    Always answers. An unknown code returns a truthful "not in the table"
    rather than a guess -- inventing a meaning for a fault is worse than
    admitting the gap.
    """
    entry = ERROR_CODES.get(code)
    if entry is None:
        return {
            "code": code,
            "description": None,
            "known": False,
            "note": ("not in the V3.9.8 manual's table. This controller runs "
                     "v3.8.5.1, for which no manual is published, so codes "
                     "may exist that are documented nowhere."),
        }
    return {
        "code": code,
        "description": entry.description,
        "process": entry.process or None,
        "seen_by_fws": entry.seen_context or None,
        "known": True,
        "source": entry.source,
    }
